CREATE TABLE public.clients (
  telegram_user_id BIGINT PRIMARY KEY,
  username TEXT,
  first_name TEXT,
  last_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_message_sender TEXT NOT NULL
    CHECK (last_message_sender IN ('client', 'bot'))
);

CREATE INDEX clients_last_message_at_idx
  ON public.clients (last_message_at DESC);

CREATE TABLE public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL
    REFERENCES public.clients (telegram_user_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  telegram_chat_id BIGINT NOT NULL,
  telegram_message_id BIGINT,
  telegram_update_id BIGINT,
  direction TEXT NOT NULL
    CHECK (direction IN ('incoming', 'outgoing')),
  message_type TEXT NOT NULL DEFAULT 'text'
    CHECK (message_type IN ('text', 'callback')),
  text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Telegram may retry the same webhook update. This index prevents duplicate
-- incoming records while still allowing NULL for outgoing messages.
CREATE UNIQUE INDEX messages_telegram_update_id_idx
  ON public.messages (telegram_update_id)
  WHERE telegram_update_id IS NOT NULL;

-- Telegram message identifiers are unique only inside a chat. Direction is
-- included because incoming and outgoing identifiers belong to separate flows.
CREATE UNIQUE INDEX messages_telegram_message_idx
  ON public.messages (direction, telegram_chat_id, telegram_message_id)
  WHERE telegram_message_id IS NOT NULL;

CREATE INDEX messages_created_at_idx
  ON public.messages (created_at DESC);

CREATE INDEX messages_client_created_at_idx
  ON public.messages (client_id, created_at DESC);

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.clients IS
  'Unique Telegram users who have interacted with the bot.';

COMMENT ON TABLE public.messages IS
  'Incoming client messages, callback actions, and outgoing bot messages.';
